### PR TITLE
Reorder columns at prediction time for glmnet

### LINKED ISSUE #273: Check at prediction time it column names are the same and in same order
##  The problem

The package {glmnet} does ignore column names at prediction time (i.e. assumes the order of the columns is the same as at training time) and only fails loudly if the number of columns supplied for prediction is not the same as at training data. Otherwise, it will return rubbish silently. The maintainer of {glmnet} does not consider the below code example a bug, but refers to `lm.fit` behaving similarly (not true for `lm` though). There are potentially other packages that just take the design matrix and don't check names.

I think in the spirit of tidy data, ignoring (the order of) column names is inappropriate. The order in which the columns appear in the supplied data should be irrelevant and column names should be respected. I think that parsnip should internally reorder predictors so they match the order supplied at training data to establish consistency across engines before passing data to the engine. This should be a cheap operation. If the names don't match, at least a warning should be issued, but probably this should even be a straight error.

## Reproducible example

``` r
# glmnet does not check column names
library(glmnet)
#> Loading required package: Matrix
#> Loaded glmnet 3.0-2
library(magrittr)
library(parsnip)

set.seed(989)
# Gaussian
x = matrix(rnorm(100 * length(letters)), 100, length(letters)) %>%
  set_colnames(letters)
y = rnorm(100)
fit1 = glmnet(x, y)

predict(fit1, newx = x[1:10, sample(colnames(x))], s = c(0.01, 0.005))
#>                  1            2
#>  [1,] -0.002009209  0.028841288
#>  [2,]  0.418464886  0.466606260
#>  [3,]  0.894231590  0.913908803
#>  [4,] -0.353718552 -0.404027790
#>  [5,]  0.553877502  0.604013668
#>  [6,] -0.432004541 -0.447641101
#>  [7,]  0.814198910  0.858768095
#>  [8,] -0.011871980 -0.004991491
#>  [9,]  0.060239108  0.147093539
#> [10,]  0.014337694  0.023354260

predict(fit1, newx = x[1:10, sample(colnames(x))], s = c(0.01, 0.005))
#>                1          2
#>  [1,] -0.5849307 -0.6117129
#>  [2,] -0.8876451 -0.9938141
#>  [3,]  0.9925675  1.0710655
#>  [4,]  0.1194124  0.1232207
#>  [5,] -0.3667705 -0.3854436
#>  [6,] -0.2561690 -0.2136745
#>  [7,]  0.7415144  0.8077588
#>  [8,] -0.7190926 -0.8195739
#>  [9,] -0.8579602 -0.8810431
#> [10,] -0.3962002 -0.3907702

# parsnip neither
model <- linear_reg() %>%
  set_engine('glmnet')
fitted <- model %>%
  fit_xy(x, y)

fitted %>%
  predict(x, penalty = 0)
#> # A tibble: 100 x 1
#>       .pred
#>       <dbl>
#>  1  0.0839 
#>  2  1.41   
#>  3 -1.41   
#>  4  0.670  
#>  5 -0.119  
#>  6 -0.484  
#>  7 -0.179  
#>  8 -0.937  
#>  9 -0.441  
#> 10 -0.00821
#> # … with 90 more rows

fitted %>%
  predict(x[, sample(colnames(x))], penalty = 0)
#> # A tibble: 100 x 1
#>     .pred
#>     <dbl>
#>  1 -0.837
#>  2  0.816
#>  3  0.102
#>  4 -0.473
#>  5  0.343
#>  6 -0.743
#>  7  0.363
#>  8 -0.682
#>  9  0.312
#> 10 -0.141
#> # … with 90 more rows
```

<sup>Created on 2020-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Ubuntu 18.04.4 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Zurich               
#>  date     2020-03-26                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.1)
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
#>  callr         3.4.1   2020-01-24 [1] CRAN (R 3.6.2)
#>  cli           2.0.1   2020-01-08 [1] CRAN (R 3.6.1)
#>  codetools     0.2-16  2018-12-24 [4] CRAN (R 3.5.2)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
#>  devtools      2.2.1   2019-09-24 [1] CRAN (R 3.6.1)
#>  digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
#>  dplyr         0.8.3   2019-07-04 [1] CRAN (R 3.6.1)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.1)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.1)
#>  foreach       1.4.8   2020-02-09 [1] CRAN (R 3.6.2)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.1)
#>  generics      0.0.2   2018-11-29 [1] CRAN (R 3.6.1)
#>  glmnet      * 3.0-2   2019-12-11 [1] CRAN (R 3.6.3)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.1)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.1)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.1)
#>  iterators     1.0.12  2019-07-26 [1] CRAN (R 3.6.2)
#>  knitr         1.27    2020-01-16 [1] CRAN (R 3.6.2)
#>  lattice       0.20-40 2020-02-19 [4] CRAN (R 3.6.2)
#>  lifecycle     0.1.0   2019-08-01 [1] CRAN (R 3.6.1)
#>  magrittr    * 1.5     2014-11-22 [1] CRAN (R 3.6.1)
#>  Matrix      * 1.2-18  2019-11-27 [4] CRAN (R 3.6.1)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
#>  parsnip     * 0.0.5   2020-01-07 [1] CRAN (R 3.6.2)
#>  pillar        1.4.3   2019-12-20 [1] CRAN (R 3.6.1)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.2)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.1)
#>  purrr         0.3.3   2019-10-18 [1] CRAN (R 3.6.1)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.1)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.1)
#>  rlang         0.4.3   2020-01-24 [1] CRAN (R 3.6.2)
#>  rmarkdown     2.0     2019-12-12 [1] CRAN (R 3.6.2)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
#>  shape         1.4.4   2018-02-07 [1] CRAN (R 3.6.2)
#>  stringi       1.4.5   2020-01-11 [1] CRAN (R 3.6.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.1)
#>  testthat      2.3.1   2019-12-01 [1] CRAN (R 3.6.1)
#>  tibble        2.1.3   2019-06-06 [1] CRAN (R 3.6.1)
#>  tidyr         1.0.0   2019-09-11 [1] CRAN (R 3.6.1)
#>  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.6.1)
#>  usethis     * 1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
#>  utf8          1.1.4   2018-05-24 [1] CRAN (R 3.6.1)
#>  vctrs         0.2.1   2019-12-17 [1] CRAN (R 3.6.1)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.3)
#>  xfun          0.12    2020-01-13 [1] CRAN (R 3.6.2)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 3.6.3)
#>  zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.6.1)
#> 
#> [1] /home/walor/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

### PR DESCRIPTION
**Pull request by juliasilge**
Closes #273.

I played around in the various `predict` functions and methods today, and I think the best place to do this reordering is in the prediction module for the two glmnet models. This is mainly because:

- the fitted object is available
- all the preprocessing has already been done

``` r
library(parsnip)
library(tidyverse)
set.seed(989)
# Gaussian
x = matrix(rnorm(100 * length(letters)), 100, length(letters)) %>%
  magrittr::set_colnames(letters)
y = rnorm(100)

glmnet_spec <- linear_reg(penalty = .1) %>%
  set_engine('glmnet')

glmnet_fit <- fit_xy(glmnet_spec, x, y)

glmnet_fit %>%
  predict(x)
#> # A tibble: 100 x 1
#>      .pred
#>      <dbl>
#>  1 -0.135 
#>  2  0.285 
#>  3 -0.126 
#>  4  0.222 
#>  5 -0.138 
#>  6 -0.157 
#>  7  0.0271
#>  8 -0.0215
#>  9 -0.0702
#> 10 -0.0283
#> # … with 90 more rows

glmnet_fit %>%
  predict(x[, sample(colnames(x))])
#> # A tibble: 100 x 1
#>      .pred
#>      <dbl>
#>  1 -0.135 
#>  2  0.285 
#>  3 -0.126 
#>  4  0.222 
#>  5 -0.138 
#>  6 -0.157 
#>  7  0.0271
#>  8 -0.0215
#>  9 -0.0702
#> 10 -0.0283
#> # … with 90 more rows



## still works with dummy variables
data(ames, package = "modeldata")

parsnip_form_fit <- glmnet_spec %>%
  fit(Sale_Price ~ Year_Built + Alley, data = ames)

predict(parsnip_form_fit, ames %>% select(Year_Built, Alley))
#> # A tibble: 2,930 x 1
#>      .pred
#>      <dbl>
#>  1 163033.
#>  2 164552.
#>  3 159996.
#>  4 175180.
#>  5 219215.
#>  6 220733.
#>  7 225289.
#>  8 211623.
#>  9 216178.
#> 10 222252.
#> # … with 2,920 more rows
```

<sup>Created on 2020-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I ran [extratests](https://github.com/tidymodels/extratests/) with this change and there were no failures related to this.

### CODE REVIEW

File: R/linear_reg_data.R [hunk 1]
```diff
@@ -168,7 +168,7 @@ set_pred(
     args =
       list(
         object = expr(object$fit),
-        newx = expr(as.matrix(new_data)),
+        newx = quote(as.matrix(new_data[, rownames(object$fit$beta)])),
```
Comment (juliasilge) [inline R/linear_reg_data.R:171]: Why was one of these `quote()` and one of these `expr()`? Which one should it be?

Comment (juliasilge) [reply R/linear_reg_data.R:171]: We want to use `expr()`

**Comment by topepo** [comment]
This needs to happen in the `poissonreg` package too.
