### PR TITLE
safe-guard ridge regression with glmnet for `poisson_reg()` and `proportional_hazards()` 

### LINKED ISSUE #861: Safe-guard Ridge regression for all glmnet engines
https://github.com/tidymodels/parsnip/issues/431 but for `poisson_reg()` and `proportional_hazards()`

https://github.com/tidymodels/parsnip/blob/2249cbb6fb2c3b2038ed8c660ff67bf2f9e06be7/R/linear_reg.R#L69-L80

### PR DESCRIPTION
**Pull request by hfrick**
closes #861

### CODE REVIEW

File: R/poisson_reg.R [hunk 1]
```diff
@@ -87,8 +87,18 @@ translate.poisson_reg <- function(x, engine = x$engine, ...) {
 
   if (engine == "glmnet") {
     .check_glmnet_penalty_fit(x)
-    # See discussion in https://github.com/tidymodels/parsnip/issues/195
-    x$method$fit$args$lambda <- NULL
+    if (any(names(x$eng_args) == "path_values")) {
```
Comment (topepo) [inline R/poisson_reg.R:90]: Maybe also add [this url](https://parsnip.tidymodels.org/reference/glmnet-details.html) since that is more readable.

Comment (hfrick) [reply R/poisson_reg.R:91]: ah, yes! I've added it for all occurrences of this code block
