### PR TITLE
Better error message for misspelling of engine packages, for engines only in extension packages

### LINKED ISSUE #1110: unhelpful error if engine is miss-specified for extension packages
``` r
library(poissonreg)
#> Loading required package: parsnip

spec <- poisson_reg() %>% 
  set_engine("gml") %>%
  set_mode("regression")

fit(spec, gear ~ ., data = mtcars)
#> Error in `fit()`:
#> ! formula_ is unknown.
```

<sup>Created on 2024-04-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
to close #1110

### CODE REVIEW

File: tests/testthat/test-poissonreg.R [hunk 1]
```diff
@@ -0,0 +1,11 @@
+test_that("misspelled engine names give informative error for extension packages", {
```
Comment (EmilHvitfeldt) [inline tests/testthat/test-poissonreg.R]: while this might have been better in a different test file, we need it here before poissonreg is loaded

Comment (topepo) [reply tests/testthat/test-poissonreg.R]: Should this go in extratests?

Comment (topepo) [reply tests/testthat/test-poissonreg.R]: Also, I would write a few tests that define the model in different orders, like: 

```r
poisson_reg() |>
    set_engine("gml") |>
    set_mode("regression")

poisson_reg() |>
    set_engine("gml") 

# etc
```

Comment (EmilHvitfeldt) [reply tests/testthat/test-poissonreg.R]: both handled in https://github.com/tidymodels/extratests/pull/298
