### PR TITLE
Make predictions respect `event_level` for xgboost

### LINKED ISSUE #460: `predict()` associates prediction with wrong class when `event_level = 'first'`
I've tested the new functionally to set `event_level = 'first'`  with the `'xgboost'` engine, and noticed that predictions when `event_level = 'first'` are being assigned to the wrong class. 

This extends to `collect_metric()` as all metric are 'backwards' e.g. auc = 1 - given auc

``` r
library(tidyverse)
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(mlbench)
library(xgboost)
#> 
#> Attaching package: 'xgboost'
#> The following object is masked from 'package:dplyr':
#> 
#>     slice
library(reprex)


data("PimaIndiansDiabetes")
df <- PimaIndiansDiabetes %>%
  mutate(diabetes = fct_relevel(diabetes, 'pos'))


# xgboost
x <- as.matrix(df[,-ncol(df)])
y <- -as.numeric(df$diabetes)+2

xgbmat <- xgb.DMatrix(data = x, label = y)

set.seed(24)
xgb_model <- xgb.train(params = list(eta = 0.3, max_depth = 3, gamma = 0, 
    colsample_bytree = 1, min_child_weight = 1, subsample = 1, 
    objective = "binary:logistic"),  watchlist = list('train' = xgbmat),
    verbose = 1, data = xgbmat, nrounds = 10, eval_metric = "auc", 
    nthread = 1)
#> [1]  train-auc:0.834787 
#> [2]  train-auc:0.853881 
#> [3]  train-auc:0.873048 
#> [4]  train-auc:0.875000 
#> [5]  train-auc:0.882873 
#> [6]  train-auc:0.891716 
#> [7]  train-auc:0.896067 
#> [8]  train-auc:0.900414 
#> [9]  train-auc:0.904313 
#> [10] train-auc:0.906937

tidy_model <- boost_tree(trees = 10, 
                         tree_depth = 3) %>%
  set_engine('xgboost', 
             eval_metric = 'auc',
             event_level = "first",
             verbose = 1) %>%
  set_mode('classification')

set.seed(24)
tidy_model_fitted <- tidy_model %>% 
  fit(diabetes ~ . , data = df)
#> [1]  training-auc:0.834787 
#> [2]  training-auc:0.853881 
#> [3]  training-auc:0.873048 
#> [4]  training-auc:0.875000 
#> [5]  training-auc:0.882873 
#> [6]  training-auc:0.891716 
#> [7]  training-auc:0.896067 
#> [8]  training-auc:0.900414 
#> [9]  training-auc:0.904313 
#> [10] training-auc:0.906937


# xgboost predictions
predict(xgb_model, newdata = xgbmat) %>%
  as_tibble() %>%
  select(.pred_pos = value) %>%
  mutate(.pred_meg = 1 - .pred_pos)
#> # A tibble: 768 x 2
#>    .pred_pos .pred_meg
#>        <dbl>     <dbl>
#>  1    0.586      0.414
#>  2    0.106      0.894
#>  3    0.778      0.222
#>  4    0.0541     0.946
#>  5    0.613      0.387
#>  6    0.0963     0.904
#>  7    0.163      0.837
#>  8    0.370      0.630
#>  9    0.834      0.166
#> 10    0.344      0.656
#> # ... with 758 more rows


# tidy model predicts are associated with the wrong class 
predict(tidy_model_fitted, new_data = df, type = 'prob')
#> # A tibble: 768 x 2
#>    .pred_pos .pred_neg
#>        <dbl>     <dbl>
#>  1     0.414    0.586 
#>  2     0.894    0.106 
#>  3     0.222    0.778 
#>  4     0.946    0.0541
#>  5     0.387    0.613 
#>  6     0.904    0.0963
#>  7     0.837    0.163 
#>  8     0.630    0.370 
#>  9     0.166    0.834 
#> 10     0.656    0.344 
#> # ... with 758 more rows

xgb_predictions <- 
  predict(xgb_model, newdata = xgbmat) %>%
  as_tibble() %>%
  select(.pred_pos = value) %>%
  mutate(.pred_meg = 1 - .pred_pos)

tidy_predictions <- predict(tidy_model_fitted, new_data = df, type = 'prob')



# Correct prediction to class
roc_auc_vec(df$diabetes, xgb_predictions$.pred_pos)
#> [1] 0.9069366

# Flipped prediction to class
roc_auc_vec(df$diabetes, tidy_predictions$.pred_pos)
#> [1] 0.09306343
```

<sup>Created on 2021-04-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

### PR DESCRIPTION
**Pull request by hfrick**
Closes #460 

The predictions previously ignored the `event_level`, they respect it now.

``` r
library(tidyverse)
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(mlbench)
library(xgboost)
#> 
#> Attaching package: 'xgboost'
#> The following object is masked from 'package:dplyr':
#> 
#>     slice
library(reprex)


data("PimaIndiansDiabetes")
df <- PimaIndiansDiabetes %>%
  mutate(diabetes = fct_relevel(diabetes, 'pos'))


# xgboost
x <- as.matrix(df[,-ncol(df)])
y <- -as.numeric(df$diabetes)+2

xgbmat <- xgb.DMatrix(data = x, label = y)

set.seed(24)
xgb_model <- xgb.train(params = list(eta = 0.3, max_depth = 3, gamma = 0, 
                                     colsample_bytree = 1, min_child_weight = 1, subsample = 1, 
                                     objective = "binary:logistic"),  watchlist = list('train' = xgbmat),
                       verbose = 1, data = xgbmat, nrounds = 10, eval_metric = "auc", 
                       nthread = 1)
#> [1]  train-auc:0.834787 
#> [2]  train-auc:0.853881 
#> [3]  train-auc:0.873048 
#> [4]  train-auc:0.875000 
#> [5]  train-auc:0.882873 
#> [6]  train-auc:0.891716 
#> [7]  train-auc:0.896067 
#> [8]  train-auc:0.900414 
#> [9]  train-auc:0.904313 
#> [10] train-auc:0.906937

tidy_model <- boost_tree(trees = 10, 
                         tree_depth = 3) %>%
  set_engine('xgboost', 
             eval_metric = 'auc',
             event_level = "first",
             verbose = 1) %>%
  set_mode('classification')

set.seed(24)
tidy_model_fitted <- tidy_model %>% 
  fit(diabetes ~ . , data = df)
#> [1]  training-auc:0.834787 
#> [2]  training-auc:0.853881 
#> [3]  training-auc:0.873048 
#> [4]  training-auc:0.875000 
#> [5]  training-auc:0.882873 
#> [6]  training-auc:0.891716 
#> [7]  training-auc:0.896067 
#> [8]  training-auc:0.900414 
#> [9]  training-auc:0.904313 
#> [10] training-auc:0.906937


# xgboost predictions
predict(xgb_model, newdata = xgbmat) %>%
  as_tibble() %>%
  select(.pred_pos = value) %>%
  mutate(.pred_meg = 1 - .pred_pos)
#> # A tibble: 768 x 2
#>    .pred_pos .pred_meg
#>        <dbl>     <dbl>
#>  1    0.586      0.414
#>  2    0.106      0.894
#>  3    0.778      0.222
#>  4    0.0541     0.946
#>  5    0.613      0.387
#>  6    0.0963     0.904
#>  7    0.163      0.837
#>  8    0.370      0.630
#>  9    0.834      0.166
#> 10    0.344      0.656
#> # … with 758 more rows

# tidy model predicts are associated with the right class now
predict(tidy_model_fitted, new_data = df, type = 'prob')
#> # A tibble: 768 x 2
#>    .pred_pos .pred_neg
#>        <dbl>     <dbl>
#>  1    0.586      0.414
#>  2    0.106      0.894
#>  3    0.778      0.222
#>  4    0.0541     0.946
#>  5    0.613      0.387
#>  6    0.0963     0.904
#>  7    0.163      0.837
#>  8    0.370      0.630
#>  9    0.834      0.166
#> 10    0.344      0.656
#> # … with 758 more rows

xgb_predictions <- 
  predict(xgb_model, newdata = xgbmat) %>%
  as_tibble() %>%
  select(.pred_pos = value) %>%
  mutate(.pred_meg = 1 - .pred_pos)

tidy_predictions <- predict(tidy_model_fitted, new_data = df, type = 'prob')


# Correct prediction to class
roc_auc_vec(df$diabetes, xgb_predictions$.pred_pos)
#> [1] 0.9069366

# now correct prediction to class
roc_auc_vec(df$diabetes, tidy_predictions$.pred_pos)
#> [1] 0.9069366
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### CODE REVIEW

File: R/boost_tree_data.R [hunk 1]
```diff
@@ -158,7 +158,12 @@ set_pred(
     pre = NULL,
     post = function(x, object) {
       if (is.vector(x)) {
-        x <- ifelse(x >= 0.5, object$lvl[2], object$lvl[1])
+        event_level <- get_event_level(object$spec)
+        if (event_level == "first") {
+          x <- ifelse(x >= 0.5, object$lvl[1], object$lvl[2])
+        } else {
+          x <- ifelse(x >= 0.5, object$lvl[2], object$lvl[1])
```
Comment (DavisVaughan) [inline R/boost_tree_data.R:165]: Whew, okay this is tricky.

So because of [this part](https://github.com/tidymodels/parsnip/pull/436/files#diff-6ba4d8e73ecfc4ae6e9828384324560ee05f46e4b7b64770e36dc14700b895e3R446-R450) of this previous PR, if `event_level = "first"` we flip around the data before handing it off to xgboost because xgboost will fit the model assuming that the second level is the one you are assuming is the "event".

So now, at prediction time, we get predictions from xgboost, and if `x >= 0.5`, it is saying that it is predicting the second class of the data we provided it, which corresponds to the _first_ level of `object$lvl`, since we originally flipped the data around.

Okay, I think that logic is correct.

Does this mean that if people get predictions from parsnip and take them to yardstick, then they would _not_ have to set the yardstick option `event_level = "second"`? Since the predictions they are getting have already accounted for that?

File: R/boost_tree_data.R [hunk 2]
```diff
@@ -158,7 +158,12 @@ set_pred(
...
+        }
       } else {
         x <- object$lvl[apply(x, 1, which.max)]
```
Comment (DavisVaughan) [inline R/boost_tree_data.R:168]: Nothing to do here right? Because it is multiclass and that isn't affected by this?

File: tests/testthat/test_boost_tree_xgboost.R [hunk 3]
```diff
@@ -210,14 +210,45 @@ test_that('submodel prediction', {
...
-  expect_equal(mp_res[[".pred_No"]], pred_class)
+  expect_equal(mp_res[[".pred_Yes"]], pred_class)
 
   expect_error(
     multi_predict(class_fit, newdata = wa_churn[1:4, vars], trees = 5, type = "prob"),
     "Did you mean"
   )
 })
 
+test_that('prediction with event_level', {
```
Comment (DavisVaughan) [inline tests/testthat/test_boost_tree_xgboost.R:221]: It might be more appropriate to check the result of using `event_level = "first"` against the result of fitting the xgboost model with `xgb.train()` and then calling `predict()` on it, i.e. what is done in the original issue here https://github.com/tidymodels/parsnip/issues/460#issue-850892494. Then we know we are matching the behavior of xgboost's fitting and prediction functions, not just the prediction part?

If you want to keep this test for both `event_level`s, you could just add a second one that also does it the way I mentioned

File: R/boost_tree_data.R (hunk 2 above)
Comment (hfrick) [reply R/boost_tree_data.R:168]: yes, that is my understanding of the code

File: tests/testthat/test_boost_tree_xgboost.R (hunk 3 above)
Comment (hfrick) [reply tests/testthat/test_boost_tree_xgboost.R]: there was already a test doing the fitting straight through {xgboost} so I combined them into one, hopefully clearer, test on `event_level`

**Review by DavisVaughan — APPROVED** [review]
