### PR TITLE
prompt on unavailable extension packages

### LINKED ISSUE #731: `translate()` print method fails uninformatively when extension isn't loaded
``` r
library(parsnip)

C5_rules() %>% translate("C5.0")
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0 
#> 
#> Model fit template:
#> Error in `call2()`:
#> ! Can't create call to non-callable object

library(rules)

C5_rules() %>% translate("C5.0")
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0 
#> 
#> Model fit template:
#> rules::c5_fit(x = missing_arg(), y = missing_arg(), weights = missing_arg())
```

<sup>Created on 2022-05-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #731.

I've had a few moments of confusion as I've familiarized with parsnip where I unknowingly specify a model specification/engine/mode combination that requires an extension package, and only come across failures later on in a modeling pipeline. This seems to be the source of confusion in #544 as well.

This PR refines print methods to nudge users to load an extension package if it's needed.

``` r
# warns informatively when it ought to:
library(parsnip)

C5_rules()
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ The parsnip extension package rules implements support for this specification.
#> ℹ Please install (if needed) and load to continue.
#> 
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0

C5_rules(engine = "C5.0") %>% translate()
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ The parsnip extension package rules implements support for this specification.
#> ℹ Please install (if needed) and load to continue.
#> 
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0

# doesn't prompt and prints out the call as before if the implementing extension is loaded:
library(rules)

C5_rules()
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0

C5_rules(engine = "C5.0") %>% translate()
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0 
#> 
#> Model fit template:
#> rules::c5_fit(x = missing_arg(), y = missing_arg(), weights = missing_arg())

# otherwise behaves the same as before:
linear_reg() %>% translate()
#> Linear Regression Model Specification (regression)
#> 
#> Computational engine: lm 
#> 
#> Model fit template:
#> stats::lm(formula = missing_arg(), data = missing_arg(), weights = missing_arg())

linear_reg()
#> Linear Regression Model Specification (regression)
#> 
#> Computational engine: lm
```

<sup>Created on 2022-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

[EDIT: updated reprex and explanation to reflect changes re: Julia's edits]

### CODE REVIEW

**Comment by juliasilge** [comment]
I think this would make the most sense in an `rlang::inform()` vs. printing (and we have a lot of tools for handling the rlang messages).

**Comment by simonpcouch** [comment]
Ah, thank you @juliasilge! I agree that `rlang::inform` likely makes more sense.

Just pushed those changes—they're a bit more invasive now but do result in a better interface.

**Comment by simonpcouch** [comment]
Wrapping up for the night, though this isn't quite there.🌝🌚

File: R/misc.R [hunk 1]
```diff
@@ -89,18 +155,10 @@ is_missing_arg <- function(x)
 show_call <- function(object) {
   object$method$fit$args <-
     map(object$method$fit$args, convert_arg)
-  if (
```
Comment (simonpcouch) [inline R/misc.R:92]: Gets rid of these conditionals as the code pointed to in the `is.null(object$method$fit$func["pkg"])` condition is what resulted in the `call2` errors noted in the issue reprex. Couldn't find coverage for those lines before this PR, so I think that code was otherwise unused.

File: R/bag_mars.R [hunk 2]
```diff
@@ -47,7 +47,7 @@ print.bag_mars <- function(x, ...) {
   cat("Bagged MARS Model Specification (", x$mode, ")\n\n", sep = "")
   model_printer(x, ...)
 
-  if (!is.null(x$method$fit$args)) {
+  if (!is.null(x$method$fit$args) && has_loaded_implementation(class(x)[1], x$engine, x$mode)) {
```
Comment (simonpcouch) [inline R/bag_mars.R:50]: Most of the files changed are of this form—the additional condition guards us from printing `"Model fit template"` and then reaching the condition that would result in the `call2` error from the issue reprex.

**Review by simonpcouch — COMMENTED** [review]
A quick self-review to give some context for changes. :)

File: R/misc.R [hunk 3]
```diff
@@ -181,10 +238,14 @@ update_dot_check <- function(...) {
 #' @export
 #' @keywords internal
 #' @rdname add_on_exports
-new_model_spec <- function(cls, args, eng_args, mode, method, engine) {
+new_model_spec <- function(cls, args, eng_args, mode, method, engine, new = TRUE) {
```
[the remark this answers is not in the document]
Comment (juliasilge) [reply R/misc.R:241]: I don't know if this is just a naming issue, but `new_model_spec(new = TRUE)` or even worse `FALSE` 😱 seems weird to me, and I am almost sure I will be super confused if I come back to this later. Do you have any ideas on this?

File: R/misc.R [hunk 4]
```diff
@@ -79,6 +79,72 @@ model_printer <- function(x, ...) {
...
+  if (nrow(avail) == 0 && nrow(all) > 0) {
+    msg <-
+      glue::glue_collapse(c(
+        msg,
+        glue::glue_collapse(c(
+          "\nThe parsnip extension package {",
+          cli::col_yellow(all$pkg[[1]]),
+          "} implements support for this specification. \n",
+          "Please install (if needed) and load to continue.\n"
+        ))
```
Comment (juliasilge) [inline R/misc.R:141]: For consistence we use the [tidyverse style guide](https://style.tidyverse.org/documentation.html#r-code) which has no special font or anything for package names:

```suggestion
        glue::glue_collapse(c(
          "\nThis specification is available in the  ",
          cli::col_yellow(all$pkg[[1]]),
          " package. \n"
        ))
```

I'm a bit worried about the `\n` in this message and how that may interact with the rlang messages. Can we use the built-in bulleting, etc instead of hardcoding new lines into the message? 

Why is this `glue_collapse()` instead of just `glue()`. Because there can be more than one? Maybe we should use the pluralization from cli?

File: R/bag_mars.R (hunk 2 above)
Comment (juliasilge) [reply R/bag_mars.R:50]: How about a new little function `is_printable_spec(x)` (or something like that) to wrap this up? I worry about us having to make changes in so many places.

File: R/misc.R (hunk 4 above)
Comment (juliasilge) [reply R/misc.R:141]: I think this function should return a named character vector, with no name for the first element, `i` for the others, etc, to be used as `message` in `rlang::inform()`.

File: R/misc.R [hunk 5]
```diff
@@ -79,6 +79,72 @@ model_printer <- function(x, ...) {
...
+    dplyr::select(-model)
+
+  if (identical(mode_, "unknown")) {
+    mode_ <- ""
+  }
+
+  msg <-
+    glue::glue(
+      "parsnip could not locate an implementation for `{spec_}` {mode_} model ",
+      "specifications using the `{engine_}` engine."
```
Comment (juliasilge) [inline R/misc.R:129]:
```suggestion
      'parsnip could not locate an implementation for `{spec_}`, for {mode_} and the  `"{engine_}"` engine'
```

I like to write long `glue()` lines using `\\` rather than manually breaking with commas. One of the benefits of glue, I think!

File: R/misc.R [hunk 6]
```diff
@@ -79,6 +79,72 @@ model_printer <- function(x, ...) {
...
+    mode_ <- c("regression", "censored regression", "classification")
+  }
+  eng_cond <- if (is.null(engine_)) {TRUE} else {quote(engine == engine_)}
+
+  avail <-
+    get_from_env(spec_) %>%
+    dplyr::filter(mode %in% mode_, !!eng_cond)
+  pars <-
+    utils::read.delim(system.file("models.tsv", package = "parsnip")) %>%
+    dplyr::filter(model == spec_, !!eng_cond, mode %in% mode_, is.na(pkg))
```
Comment (juliasilge) [inline R/misc.R:99]: Is this an expensive check to do every time `new_model_spec()` is run (which is run a lot, I think)? The `env` is just there, but what about reading the file?

**Review by juliasilge — COMMENTED** [review]
It will be a huge help to give more useful info in this situation! 🙌 

I've got a bit of specific feedback and then some questions about the approach.

File: R/bag_mars.R (hunk 2 above)
Comment (simonpcouch) [reply R/bag_mars.R]: I agree that this conditional is a bit gnarly, especially given how many places it appears. Went ahead and implemented your change + I’m planning to follow up this PR with a refactor of print methods that should reduce this duplication quite a bit. :)

File: R/misc.R (hunk 4 above)
Comment (simonpcouch) [reply R/misc.R]: Thank you for the nudges on making better use of glue and inform—learned a lot about those functions from your comments.

The message now reads:

``` r
library(parsnip)

C5_rules()
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ  The parsnip extension package rules implements support for this specification.
#> ℹ  Please install (if needed) and load to continue.
#> 
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0

C5_rules(engine = "C5.0") %>% translate()
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ  The parsnip extension package rules implements support for this specification.
#> ℹ  Please install (if needed) and load to continue.
#> 
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0
```

<sup>Created on 2022-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

and the code to get there is a good bit cleaner.

(Acknowledgement that I’m a serial violator of the no-special-package-name-formatting convention.🫠  Sorry.)

File: R/misc.R (hunk 6 above)
Comment (simonpcouch) [reply R/misc.R:99]: Certainly more expensive than our other checks. But—

* It’s only run on initiation of new model types (i.e. never at `set_engine`, `update`, etc)
* It’s possibly negligible compared to fit times:

``` r
library(parsnip)

# running the check
system.time(mod <- C5_rules())
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ The parsnip extension package rules implements support for this specification.
#> ℹ Please install (if needed) and load to continue.
#>    user  system elapsed 
#>   0.038   0.001   0.039

# doesn't run the check
system.time(mod <- mod %>% set_engine("C5.0"))
#>    user  system elapsed 
#>   0.008   0.000   0.009

# model fit to a lil fella
library(rules)

mtcars$cyl <- as.factor(mtcars$cyl)

system.time(mod %>% fit(cyl ~ ., mtcars))
#>    user  system elapsed 
#>   0.445   0.020   0.467
```

<sup>Created on 2022-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

File: R/misc.R [hunk 7]
```diff
@@ -79,6 +79,75 @@ model_printer <- function(x, ...) {
...
+    mode_ <- ""
+  }
+
+  msg <-
+    glue::glue(
+      "parsnip could not locate an implementation for `{spec_}` {mode_} model \\
+       specifications using the `{engine_}` engine."
+    )
+
+  if (nrow(avail) == 0 && nrow(all) > 0) {
```
Comment (juliasilge) [inline R/misc.R:137]: Can we add a test that prints the first msg but not this bit?

File: R/misc.R [hunk 8]
```diff
@@ -79,6 +79,75 @@ model_printer <- function(x, ...) {
...
+  !is.null(x$method$fit$args) &&
+  has_loaded_implementation(class(x)[1], x$engine, x$mode)
+}
+
+# construct a message informing the user that there are no
+# implementations for the current model spec / mode / engine.
+#
+# if there's a "pre-registered" extension supporting that setup,
+# nudge the user to install/load it.
+prompt_missing_implementation <- function(spec_, engine_, mode_) {
```
Comment (juliasilge) [inline R/misc.R:118]:
```suggestion
inform_missing_implementation <- function(spec_, engine_, mode_) {
```
This will help for future reading, I think, to clarify what this is being used for

File: R/misc.R (hunk 6 above)
Comment (juliasilge) [reply R/misc.R:99]: The fact that it could be common to read this file multiple times seems like something to check and get other feedback on. We could read this file one time at `.onLoad` or something? Let's have one more person look at this part of the PR and see what they think.

File: R/misc.R (hunk 3 above)
[the remark this answers is not in the document]
Comment (juliasilge) [reply R/misc.R:244]: What do you think about `check_missing_spec = TRUE`? Since this argument is less about whether the spec is new or not and more about whether it will be checked?

**Review by juliasilge — CHANGES_REQUESTED** [review]

File: R/misc.R (hunk 3 above)
[the remark this answers is not in the document]
Comment (simonpcouch) [reply R/misc.R]: That's definitely better—4dd0fb9.

File: R/misc.R (hunk 8 above)
Comment (simonpcouch) [reply R/misc.R]: Sure thing—6c06315!

File: R/misc.R (hunk 6 above)
Comment (simonpcouch) [reply R/misc.R]: I think that's a good observation. After [9918043](https://github.com/tidymodels/parsnip/pull/732/commits/9918043a135e0782d40f3233335642f23666c53f), parsnip now assigns the `models.tsv` system file as `model_info_table` internally so we can skip that load step on checks:

``` r
library(parsnip)
  
# now just assigns models.tsv to internal object:
head(parsnip:::model_info_table)
#>      model                mode engine      pkg
#> 1 bag_mars      classification  earth baguette
#> 2 bag_mars          regression  earth baguette
#> 3 bag_tree censored regression  rpart censored
#> 4 bag_tree      classification   C5.0 baguette
#> 5 bag_tree      classification  rpart baguette
#> 6 bag_tree          regression  rpart baguette

# running the check. used to be:
#>    user  system elapsed 
#>   0.038   0.001   0.039
system.time(mod <- C5_rules())
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ The parsnip extension package rules implements support for this specification.
#> ℹ Please install (if needed) and load to continue.
#>    user  system elapsed 
#>   0.033   0.001   0.033


# doesn't run the check. used to be:
#>    user  system elapsed 
#>   0.008   0.000   0.009
system.time(mod <- mod %>% set_engine("C5.0"))
#>    user  system elapsed 
#>   0.007   0.000   0.007


# model fit to a lil fella, for comparison
library(rules)

mtcars$cyl <- as.factor(mtcars$cyl)

system.time(mod %>% fit(cyl ~ ., mtcars))
#>    user  system elapsed 
#>   0.440   0.025   0.464
```

<sup>Created on 2022-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I opted not to ditch that `models.tsv` file entirely as it seems our machinery to keep it updated with the current docs system works well.

**Comment by simonpcouch** [comment]
This should be ready for your review, @topepo! 

One unresolved discussion that we'd especially appreciate your eye on: https://github.com/tidymodels/parsnip/pull/732#discussion_r880971596

File: R/misc.R (hunk 7 above)
Comment (juliasilge) [reply R/misc.R:140]: Am I just missing seeing a test like this?

Comment (simonpcouch) [reply R/misc.R:140]: Oh, woops—somehow missed this. Added in [51ffc03](https://github.com/tidymodels/parsnip/pull/732/commits/51ffc0371f3f9d398a2a27733202b5131f4b7073). :)

**Review by juliasilge — APPROVED** [review]

File: R/misc.R [hunk 9]
```diff
@@ -79,6 +79,78 @@ model_printer <- function(x, ...) {
 is_missing_arg <- function(x)
   identical(x, quote(missing_arg()))
 
+model_info_table <-
+  utils::read.delim(system.file("models.tsv", package = "parsnip"))
```
Comment (topepo) [inline R/misc.R:83]: Can you do the same without using this file? The parsnip model env is the best representation of when packages are required for an engine.

Comment (simonpcouch) [reply R/misc.R:83]: @topepo I'm not sure we can.

Could you confirm that the needed extension package is not reflected in the model environment if that package is not loaded? e.g.

``` r
library(parsnip)
  
m_env <- parsnip::get_model_env()
m_env$C5_rules_pkgs
#> # A tibble: 0 × 3
#> # … with 3 variables: engine <chr>, pkg <list>, mode <chr>
m_env$C5_rules
#> # A tibble: 0 × 2
#> # … with 2 variables: engine <chr>, mode <chr>

C5_rules()
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ The parsnip extension package rules implements support for this specification.
#> ℹ Please install (if needed) and load to continue.
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0

library(rules)

m_env_ <- parsnip::get_model_env()
m_env_$C5_rules_pkgs
#> # A tibble: 1 × 3
#>   engine pkg       mode          
#>   <chr>  <list>    <chr>         
#> 1 C5.0   <chr [2]> classification

C5_rules()
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0
```

<sup>Created on 2022-05-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Using the model environment instead wouldn't supply the information we need, I think—the purpose of this prompt is to nudge users to load a specific, needed extension package into their model environment if we can identify which one they need.

Comment (simonpcouch) [reply R/misc.R:83]: (Discussed in meeting—thumbs up from Max here.)

**Comment by simonpcouch** [comment]
Note from meeting: thumbs up from Max to merge!
